Repository 0x5bfa/FluentHub, pull requests merged in 2022-08, with the labels that each got.

#223 New Crowdin updates
  crowdin.yml
  src/FluentHub.Uwp/Strings/af-ZA/Resources.resw
  src/FluentHub.Uwp/Strings/ar-SA/Resources.resw
  src/FluentHub.Uwp/Strings/bg-BG/Resources.resw
  src/FluentHub.Uwp/Strings/de-DE/Resources.resw
  src/FluentHub.Uwp/Strings/el-GR/Resources.resw
  src/FluentHub.Uwp/Strings/es-419/Resources.resw
  src/FluentHub.Uwp/Strings/fil-PH/Resources.resw
  src/FluentHub.Uwp/Strings/fr-FR/Resources.resw
  src/FluentHub.Uwp/Strings/he-IL/Resources.resw
  src/FluentHub.Uwp/Strings/hi-IN/Resources.resw
  src/FluentHub.Uwp/Strings/hu-HU/Resources.resw
  src/FluentHub.Uwp/Strings/id-ID/Resources.resw
  src/FluentHub.Uwp/Strings/it-IT/Resources.resw
  src/FluentHub.Uwp/Strings/ka-GE/Resources.resw
  src/FluentHub.Uwp/Strings/ko-KR/Resources.resw
  src/FluentHub.Uwp/Strings/lv-LV/Resources.resw
  src/FluentHub.Uwp/Strings/no-NO/Resources.resw
  src/FluentHub.Uwp/Strings/pl-PL/Resources.resw
  src/FluentHub.Uwp/Strings/pt-BR/Resources.resw
  src/FluentHub.Uwp/Strings/pt-PT/Resources.resw
  src/FluentHub.Uwp/Strings/ru-RU/Resources.resw
  src/FluentHub.Uwp/Strings/sk-SK/Resources.resw
  src/FluentHub.Uwp/Strings/sv-SE/Resources.resw
  src/FluentHub.Uwp/Strings/ta-IN/Resources.resw
  src/FluentHub.Uwp/Strings/th-TH/Resources.resw
  src/FluentHub.Uwp/Strings/tr-TR/Resources.resw
  src/FluentHub.Uwp/Strings/uk-UA/Resources.resw
  src/FluentHub.Uwp/Strings/vi-VN/Resources.resw
  src/FluentHub.Uwp/Strings/zh-CN/Resources.resw
  src/FluentHub.Uwp/Strings/zh-TW/Resources.resw
Labels: needs review, localization, triage approved, translation

#225 General Updates 15
  README.md
  builds/azure-pipelines-release.yml
  src/FluentHub.Octokit.Generation/Properties/launchSettings.json
  src/FluentHub.Octokit/Queries/Repositories/TreeQueries.cs
  src/FluentHub.Octokit/Queries/Users/NotificationQueries.cs
  src/FluentHub.Uwp/App.xaml
  src/FluentHub.Uwp/Assets/Glyphs/Octicons.ttf
  src/FluentHub.Uwp/FluentHub.Uwp.csproj
  src/FluentHub.Uwp/Package.appxmanifest
  src/FluentHub.Uwp/UserControls/Blocks/FileNavigationBlock.xaml
  src/FluentHub.Uwp/UserControls/Blocks/LatestCommitBlock.xaml
  src/FluentHub.Uwp/UserControls/Blocks/Timeline.xaml
  src/FluentHub.Uwp/UserControls/ButtonBlocks/IssueButtonBlock.xaml
  src/FluentHub.Uwp/UserControls/ButtonBlocks/NotificationButtonBlock.xaml
  src/FluentHub.Uwp/UserControls/ButtonBlocks/ProjectButtonBlock.xaml
  src/FluentHub.Uwp/UserControls/ButtonBlocks/PullButtonBlock.xaml
  src/FluentHub.Uwp/UserControls/ButtonBlocks/RepoButtonBlock.xaml
  src/FluentHub.Uwp/UserControls/GitCloneFlyout.xaml
  src/FluentHub.Uwp/UserControls/Labels/StateLabel.xaml
  src/FluentHub.Uwp/UserControls/Overview/OrganizationProfileOverview.xaml
  src/FluentHub.Uwp/UserControls/Overview/PullRequestOverview.xaml
  src/FluentHub.Uwp/UserControls/Overview/RepositoryOverview.xaml
  src/FluentHub.Uwp/UserControls/Overview/UserProfileOverview.xaml
  src/FluentHub.Uwp/Views/AppSettings/Accounts/AccountPage.xaml
  src/FluentHub.Uwp/Views/AppSettings/Accounts/OtherUsersPage.xaml
  src/FluentHub.Uwp/Views/Home/FeedsPage.xaml
  src/FluentHub.Uwp/Views/Home/UserHomePage.xaml
  src/FluentHub.Uwp/Views/Organizations/ProfilePage.xaml
  src/FluentHub.Uwp/Views/Repositories/Codes/Layouts/DetailsLayoutView.xaml
  src/FluentHub.Uwp/Views/Repositories/Codes/Layouts/TreeLayoutView.xaml
  src/FluentHub.Uwp/Views/Repositories/Issues/IssuePage.xaml
  src/FluentHub.Uwp/Views/Repositories/Issues/IssuesPage.xaml
  src/FluentHub.Uwp/Views/Repositories/OverviewPage.xaml
  src/FluentHub.Uwp/Views/Repositories/PullRequests/ConversationPage.xaml
  src/FluentHub.Uwp/Views/Repositories/PullRequests/PullRequestPage.xaml
  src/FluentHub.Uwp/Views/Users/ProfilePage.xaml
Labels: general updates

#235 Update azure-pipelines.yml for Azure Pipelines
  builds/FluentHub-CI.yml
  builds/FluentHub-PR.yml
  builds/azure-pipelines.yml
Labels: project improvements

#238 Update Search Bar
  src/FluentHub.Uwp/Views/MainPage.xaml
  src/FluentHub.Uwp/Views/MainPage.xaml.cs
Labels: change requested, approved, priority-medium

#245 Fix typo in docs
  docs/credentials.md
Labels: approved, project improvements
