Repository 0x5bfa/FluentHub, pull requests merged in 2022-09, with the labels that each got.

#250 Number normalizer
  src/FluentHub.Octokit/Queries/Users/NotificationQueries.cs
  src/FluentHub.Uwp/FluentHub.Uwp.csproj
  src/FluentHub.Uwp/Helpers/NumberNormalizerHelper.cs
  src/FluentHub.Uwp/UserControls/Overview/RepositoryOverview.xaml
  src/FluentHub.Uwp/UserControls/Overview/RepositoryOverview.xaml.cs
Labels: priority-low, area-repository

#244 Localize FluentHub
  src/FluentHub.Uwp/Helpers/NumberNormalizerHelper.cs
  src/FluentHub.Uwp/Strings/en-US/Resources.resw
  src/FluentHub.Uwp/Views/AppSettings/AppearancePage.xaml
  src/FluentHub.Uwp/Views/Home/FeedsPage.xaml
  src/FluentHub.Uwp/Views/Home/NotificationsPage.xaml
  src/FluentHub.Uwp/Views/Home/UserHomePage.xaml
  src/FluentHub.Uwp/Views/MainPage.xaml
Labels: approved

#252 New Crowdin updates
  src/FluentHub.Uwp/Strings/af-ZA/Resources.resw
  src/FluentHub.Uwp/Strings/ar-SA/Resources.resw
  src/FluentHub.Uwp/Strings/bg-BG/Resources.resw
  src/FluentHub.Uwp/Strings/de-DE/Resources.resw
  src/FluentHub.Uwp/Strings/el-GR/Resources.resw
  src/FluentHub.Uwp/Strings/en-GB/Resources.resw
  src/FluentHub.Uwp/Strings/en-US/Resources.resw
  src/FluentHub.Uwp/Strings/es-419/Resources.resw
  src/FluentHub.Uwp/Strings/es-ES/Resources.resw
  src/FluentHub.Uwp/Strings/fil-PH/Resources.resw
  src/FluentHub.Uwp/Strings/fr-FR/Resources.resw
  src/FluentHub.Uwp/Strings/he-IL/Resources.resw
  src/FluentHub.Uwp/Strings/hi-IN/Resources.resw
  src/FluentHub.Uwp/Strings/hu-HU/Resources.resw
  src/FluentHub.Uwp/Strings/id-ID/Resources.resw
  src/FluentHub.Uwp/Strings/it-IT/Resources.resw
  src/FluentHub.Uwp/Strings/ja-JP/Resources.resw
  src/FluentHub.Uwp/Strings/ka-GE/Resources.resw
  src/FluentHub.Uwp/Strings/ko-KR/Resources.resw
  src/FluentHub.Uwp/Strings/lv-LV/Resources.resw
  src/FluentHub.Uwp/Strings/nb-NO/Resources.resw
  src/FluentHub.Uwp/Strings/nl-NL/Resources.resw
  src/FluentHub.Uwp/Strings/nn-NO/Resources.resw
  src/FluentHub.Uwp/Strings/pl-PL/Resources.resw
  src/FluentHub.Uwp/Strings/pt-BR/Resources.resw
  src/FluentHub.Uwp/Strings/pt-PT/Resources.resw
  src/FluentHub.Uwp/Strings/ru-RU/Resources.resw
  src/FluentHub.Uwp/Strings/sk-SK/Resources.resw
  src/FluentHub.Uwp/Strings/sv-SE/Resources.resw
  src/FluentHub.Uwp/Strings/ta-IN/Resources.resw
  src/FluentHub.Uwp/Strings/th-TH/Resources.resw
  src/FluentHub.Uwp/Strings/tr-TR/Resources.resw
  src/FluentHub.Uwp/Strings/uk-UA/Resources.resw
  src/FluentHub.Uwp/Strings/vi-VN/Resources.resw
  src/FluentHub.Uwp/Strings/zh-CN/Resources.resw
  src/FluentHub.Uwp/Strings/zh-TW/Resources.resw
Labels: localization

#301 Fix grammar in README
  README.md
Labels: change requested

#309 Update project report templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/tracker.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature request, project improvements

#313 Refactor project bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: approved
